# Generated by Django 5.2.9 on 2025-12-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_supportmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='card_style',
            field=models.CharField(default='Virtual', max_length=20),
        ),
    ]
