# Generated by Django 5.2.9 on 2025-12-07 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_account_transaction_pin_alter_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='pin_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('pending', 'Pending'), ('failed', 'Failed'), ('processing', 'Processing')], default='pending', max_length=20),
        ),
    ]
