# Generated by Django 5.2.9 on 2025-12-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_transaction_rejection_reason_alter_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='check_image',
            field=models.ImageField(blank=True, null=True, upload_to='checks'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
