# Generated by Django 5.2.9 on 2025-12-09 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_transaction_check_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
    ]
