# Generated by Django 5.2.9 on 2025-12-09 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_account_dark_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='account',
            name='hide_balance',
            field=models.BooleanField(default=False),
        ),
    ]
