# Generated by Django 5.2.9 on 2025-12-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_account_credit_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='check_back_image',
            field=models.ImageField(blank=True, null=True, upload_to='checks'),
        ),
    ]
