# Generated by Django 5.2.9 on 2025-12-13 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_transaction_check_back_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='id_card_back',
            field=models.ImageField(blank=True, null=True, upload_to='kyc'),
        ),
        migrations.AddField(
            model_name='account',
            name='id_card_front',
            field=models.ImageField(blank=True, null=True, upload_to='kyc'),
        ),
    ]
