# Generated by Django 5.2.9 on 2025-12-13 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_account_id_card_back_account_id_card_front'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='loan',
            name='term_months',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='loan',
            name='total_repayment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Active'), ('rejected', 'Rejected'), ('paid', 'Paid Off')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer', 'Transfer'), ('wire', 'Wire Transfer'), ('payment', 'Bill Payment'), ('loan', 'Loan Credit'), ('repayment', 'Loan Repayment')], default='transfer', max_length=20),
        ),
    ]
