# Generated by Django 5.0.2 on 2026-01-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_supportsession_supportmessage_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer', 'Transfer'), ('wire', 'Wire Transfer'), ('payment', 'Bill Payment'), ('loan', 'Loan Credit'), ('repayment', 'Loan Repayment'), ('refund', 'Refund / Reversal')], default='transfer', max_length=20),
        ),
    ]
